### ISSUE TITLE
webui alerts don't work with docker compose

### ISSUE THREAD

**Issue by landism** [windmilleng/tilt#1869]
Our [TS ResourceInfo type](https://github.com/windmilleng/tilt/blob/ed5d8ca9256c757085a5a4d520524cfa48b471d4/web/src/types.ts#L61) seems defined to match our [go K8sResourceInfo type](https://github.com/windmilleng/tilt/blob/a15aef07a4ba97e111081480490548a1bf7b2bfa/internal/hud/webview/view.go#L42), and doesn't handle [DCResourceInfo](https://github.com/windmilleng/tilt/blob/a15aef07a4ba97e111081480490548a1bf7b2bfa/internal/hud/webview/view.go#L18) data.

repro:
run a docker-compose project, change one of the dockerfiles to have `entrypoint exit 1`

observed:
Tilt recognizes there's an error in the statusbar, but doesn't show an alert, and clicking the "1 error" link takes you to the alerts page which says "No alerts found"
The TUI shows the container status as "Crash", but that doesn't appear anywhere in the web UI.

**Comment by maiamcc** [comment]
@landism does that PR mean that this ticket is resolved?

**Comment by landism** [comment]
nope, more like that PR was highlighting that this was still a problem

**Comment by maiamcc** [comment]
FYI @mariavivanco, can run a subset of servantes via DC: `tilt up --file=Tiltfile.dc`
