### ISSUE TITLE
tilt down should be able to target specific services

### ISSUE THREAD

**Issue by tmc** [windmilleng/tilt#2174]

**Comment by maiamcc** [comment]
To confirm I understand:

Tilt is running services A, B, and C. You want to be able to run `tilt down C` and leave A and B running?

**Comment by rpocase** [comment]
@maiamcc That would be my interpretation. I was looking for a way for `tilt down` to target specific resources (ideally, with defaults being configurable within Tiltfile).

**Comment by maiamcc** [comment]
@rpocase that makes sense! Would love to hear anything more about your use case that you care to share.

**Comment by rpocase** [comment]
Sure! We have a wrapper that starts a k3d cluster, runs `tilt up`, and runs `tilt down` after cancel (ctrl+c). Tiltfile deploys a set of resources our app depends on that does not change often but takes several minutes to deploy and configure. We also run unit+integration tests in-cluster with tilt, but we occasionally need to wipe a database to get back to a clean state. Running `tilt down` is the fastest way to do so without additional extra tooling. Marking the first set of resources as `rm=False` (by default) would let us redeploy the rest of the application from an effectively clean state in under a minute. 

We deploy both the dependent app and our in-development app through separate `k8s_yaml(helm(...))` calls.

I could image a couple useful extensions to `tilt down` e.g.
- `k8s_yaml(..., rm=True)`: mark if tilt down should remove this resource by default, similar to naming in #2427)
-  `tilt down [options] [<resource1> <resource2> ...]`:  remove only the specified resources

The question on the latter extension would be what makes sense to remove. E.g., in my case I really want to say `tilt down mydatabase` and have any volumes/deployments/etc associated with this resource destroyed. I imagine it would be hard for tilt to make assumptions about this given the various supported methods of providing yaml. Perhaps more useful would be a `tilt down --field-selector` to delete resources matching a given `field-selector`. The idea would be any resource (deployment, service, volumes, etc) uniquely associated with `mydatabase` likely has a common, unique label associated with it.

**Comment by rpocase** [comment]
For the time being, I expect [this slack thread](https://kubernetes.slack.com/archives/CESBL84MV/p1578413914068000?thread_ts=1578408416.065700&cid=CESBL84MV) from @nicks will be sufficient for my current use case. 

For anyone without slack - avoid removing specific resources by using environment variables set when running `tilt down`
```
OMIT_DB=true tilt down
```

```
#Tiltfile
if not os.environ.get('OMIT_DB', ''):
  k8s_yaml('./db.yaml')
```

This doesn't solve a case where I have resources that should be kept and resources that should be deleted mixed into a single `k8s_yaml` call (e.g., if I had a helm chart that bundles a database and I want the db omitted but destroy everything else).

**Comment by landism** [comment]
This is kind of resolved by #2848, with the caveat for "uncategorized" yaml described [here](https://github.com/windmilleng/tilt/issues/2820#issuecomment-578937011).

I think we need to provide a way users to put all yaml into resources and avoid tilt's automatic "uncategorized" resource, for things such as volumes mentioned above.

**Comment by nicks** [comment]
I'm going to mark this as closed, since it sounds like the new config support (https://docs.tilt.dev/tiltfile_config.html) allows Tiltfiles to support this.

If that doesn't resolve the problem, happy to continue chatting on this thread or in a separate issue
